version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24

services:
  sbt:
    container_name: sbt
    image: mozilla/sbt:8u232_1.3.13
    networks:
      - arc-integration
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app
      - /tmp/pgp:/pgp
    working_dir: /app

  mongo:
    image: mongo:4.2.8-bionic
    networks:
      - arc-integration
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: arc
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
