version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24  

services:
  sbt:
    container_name: sbt
    image: mozilla/sbt:8u212_1.2.8 
    networks:
      - arc-integration     
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app  
      - /tmp/pgp:/pgp
    working_dir: /app

  mongo:
    image: mongo:3.4.21-xenial
    networks:
      - arc-integration
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: arc
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - arc-integration      
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example